services:
  # Backend Service
  - type: web
    name: label-app-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python seed.py && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
    branch: main
    rootDir: .

databases:
  - name: labelapp-db
    databaseName: labelapp
    user: labelapp
    plan: free
